discussion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),    
]

todolist/urls.py
from django.urls import path
from . import views

# Syntax
# path(route, view, name)

app_name = 'todolist'

urlpatterns = [
	path('', views.index, name='index'),
	path('index', views.index, name='index'),
	path('register', views.register, name='register'),
	path('change_password', views.change_password, name='change_password'),
	path('login', views.login_view, name='login'),
	path('logout', views.logout_view, name="logout"),
	path('add_task', views.add_task, name="add_task"),
	path('<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
	path('<int:todoitem_id>/edit', views.update_task, name='update_task'),
	path('<int:todoitem_id>/delete', views.delete_task, name='delete_task'),
	path('add_event', views.add_event, name="add_event"),
	path('event/<int:eventitem_id>/', views.eventitem, name='vieweventitem'),
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ToDoItem(models.Model):
	task_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

class EventItem(models.Model):
	event_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

todolist/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	password = forms.CharField(label='Password', max_length=20)

class AddTaskForm(forms.Form):
	task_name = forms.CharField(label='Task Name', max_length=50)
	description = forms.CharField(label='Description', max_length=200)

class UpdateTaskForm(forms.Form):
	task_name = forms.CharField(label='Task Name', max_length=50)
	description = forms.CharField(label='Description', max_length=200)
	status = forms.CharField(label='Status',max_length=50)

class RegisterForm(forms.Form):
	username = forms.CharField(label='Username', max_length=50)
	password = forms.CharField(label='Password', max_length=20)
	confirm_password = forms.CharField(label='Confirm Password', max_length=20)
	first_name = forms.CharField(label='First Name', max_length=50)
	last_name = forms.CharField(label='Last Name', max_length=50)
	email = forms.CharField(label='Email', max_length=50)

class AddEventForm(forms.Form):
	event_name = forms.CharField(label='Task Name', max_length=50)
	description = forms.CharField(label='Description', max_length=200)

todolist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
# from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.utils import timezone

from .models import ToDoItem, EventItem
from .forms import LoginForm, AddTaskForm, UpdateTaskForm, RegisterForm, AddEventForm

def index(request):
	todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
	eventitem_list = EventItem.objects.filter(user_id=request.user.id)

	context = {
		'todoitem_list': todoitem_list,
		'eventitem_list': eventitem_list,
		'user': request.user
		}

	return render(request, "todolist/index.html", context)

def todoitem(request, todoitem_id):
	
	todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)

	return render(request, "todolist/todoitem.html", model_to_dict(todoitem))

def eventitem(request, eventitem_id):
	
	eventitem = get_object_or_404(EventItem, pk=eventitem_id)

	return render(request, "todolist/eventitem.html", model_to_dict(eventitem))


def register(request):
    users = User.objects.all()

    is_user_registered = False
    is_same_password = True
    context = {
    "is_user_registered": is_user_registered,
    "is_same_password": is_same_password
    }

    if request.method == 'POST':

        form = RegisterForm(request.POST)

        if form.is_valid() == False:

            form = RegisterForm()

        else:

            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            confirm_password = form.cleaned_data['confirm_password']
            user = authenticate(username=username, password=password)
            context = {
                "username": username,
                "password": password
            }

            for indiv_user in users:
                if indiv_user.username == username:
                    is_user_registered = True
                    break


            if is_user_registered == False:
                user = User()
                user.username = username
                user.first_name = first_name
                user.last_name = last_name
                user.email = email
                user.set_password(password)
                user.confirm_password = confirm_password

                
                user.is_staff = False
                user.is_active = True
                user.save()
                context = {
                "first_name": user.first_name,
                "last_name": user.last_name
                }

    return render(request, "todolist/register.html", context)


def change_password(request):
	is_user_authenticated = False

	user = authenticate(username="johndoe", password="johndoe1")
	print(user)

	if user is not None:
		# user = User.objects.get(username='johndoe')
		# user.set_password("johndoe1")
		# user.save()
		# is_user_authenticated = True
		authenticated_user = User.objects.get(username='johndoe')
		authenticated_user.set_password("johndoe1")
		authenticated_user.save()
		is_user_authenticated = True

	context = {
		"is_user_authenticated": is_user_authenticated
	}

	return render(request, "todolist/change_password.html", context)

def login_view(request):


	context = {}

	if request.method == 'POST':

		form = LoginForm(request.POST)


		if form.is_valid() == False:

			form = LoginForm()

		else:

			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(username=username, password=password)
			context = {
				"username": username,
				"password": password
			}

		if user is not None:
			login(request, user)
			return redirect("todolist:index")

		else:
			context = {
				"error": True
			}

	return render(request, "todolist/login.html", context)

def logout_view(request):
	logout(request)
	return redirect("todolist:index")

def add_task(request):

	context = {}

	if request.method == 'POST':

		form = AddTaskForm(request.POST)

		if form.is_valid() == False:

			form = AddTaskForm()

		else:

			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']

			duplicates = ToDoItem.objects.filter(task_name=task_name)

			if not duplicates:

				ToDoItem.objects.create(task_name=task_name, description=description, date_created=timezone.now(), user_id=request.user.id)
				return redirect("todolist:index")

			else:

				context = {
					"error": True
				}

	return render(request, "todolist/add_task.html", context)

def update_task(request, todoitem_id):

	todoitem = ToDoItem.objects.filter(pk=todoitem_id)

	context = {
		"user": request.user,
		"todoitem_id": todoitem_id,
		"task_name": todoitem[0].task_name,
		"description": todoitem[0].task_name,
		"status": todoitem[0].status
	}

	if request.method == 'POST':

		form = UpdateTaskForm(request.POST)

		if form.is_valid() == False:

			form = UpdateTaskForm()

		else:

			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status'] 

			if todoitem:

				todoitem[0].task_name = task_name
				todoitem[0].description = description
				todoitem[0].status = status

				todoitem[0].save()
				return redirect("todolist:index")

			else:

				context = {
					"error": True
				}

	return render(request, "todolist/update_task.html", context)

def delete_task(request, todoitem_id):
	
	todoitem = ToDoItem.objects.filter(pk=todoitem_id).delete()
	return redirect("todolist:index")

def add_event(request):

	context = {}

	if request.method == 'POST':

		form = AddEventForm(request.POST)

		if form.is_valid() == False:

			form = AddEventForm()

		else:

			event_name = form.cleaned_data['event_name']
			description = form.cleaned_data['description']

			duplicates = EventItem.objects.filter(event_name=event_name)

			if not duplicates:

				EventItem.objects.create(event_name=event_name, description=description, user_id=request.user.id)
				return redirect("todolist:index")

			else:

				context = {
					"error": True
				}

	return render(request, "todolist/add_event.html", context)

todolist/templates/todolist/add_event.html
{% extends 'base.html' %}

{% block title %}Add Event{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Add An Event</h1>
				{% if error == True %}
					<p class="text-danger">Duplicate event found</p>
				{% endif %}
				<form action="{% url 'todolist:add_event' %}" method="post">
				{% csrf_token %}

					<div class="mb-3">
						<label for="event_name">Event Name:</label>
						<input class="form-control" id="event_name" type="text" name="event_name" value="{{ event_name }}" maxlength="20" required>
					</div>

					<div class="mb-3">
						<label for="description">Description:</label>
						<textarea class="form-control" name="description" value="{{ description }}" required></textarea>
					</div>

					<div class="text-center">
						<input class="btn btn-success" type="submit" value="Add Event">
					</div>
				</form>

			</div>
		</div>
	</div>
{% endblock %}

todolist/templates/todolist/add_task.html
{% extends 'base.html' %}

{% block title %}Add Task{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Add A Task</h1>
				{% if error == True %}
					<p class="text-danger">Duplicate task found</p>
				{% endif %}
				<form action="{% url 'todolist:add_task' %}" method="post">
				{% csrf_token %}

					<div class="mb-3">
						<label for="task_name">Task Name:</label>
						<input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="20" required>
					</div>

					<div class="mb-3">
						<label for="description">Description:</label>
						<textarea class="form-control" name="description" value="{{ description }}" required></textarea>
					</div>

					<div class="text-center">
						<input class="btn btn-success" type="submit" value="Add Task">
					</div>
				</form>

			</div>
		</div>
	</div>
{% endblock %}

todolist/templates/todolist/change_password.html
{% if is_user_authenticated == False %}
	<h1>Invalid User Credentials</h1>
	<p>Check if the username and password is correct.</p>
{% else %}
	<h1>User Password Successfully Updated!</h1>
	<p>The password has beed successfully changed.</p>
{% endif %}

todolist/templates/todolist/eventitem.html
{% extends 'base.html' %}

{% block title %}{{ event_name }}{% endblock %}

{% block content %}
<div class="text-center my-3">
	<h1>{{ event_name }}</h1>
	<h3>Description</h3>
	<p>{{ description }}</p>
	<h3>Status</h3>
	<p>{{ status }}</p>

	<button class="btn btn-warning mx-1 text-decoration-none">
		<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">Back to Events</a>
	</button>

</div>

{% endblock %}

todolist/templates/todolist/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}


{% block content %}
	{% if todoitem_list and user.is_anonymous == False %}
		<h1 class="text-center my-3">Welcome {{user.first_name}} {{user.last_name}}!</h1>
		<div class="container">
			<div class="row mb-3">
				<h3 class="text-center mb-3">My Tasks</h3>
				<ul class="list-group col-lg-2 offset-lg-5 text-center">
				{% for todoitem in todoitem_list %}
					<li class="list-group-item">
						<a href="{% url 'todolist:viewtodoitem' todoitem.id %}" class="text-decoration-none">{{todoitem.task_name}}</a>
					</li>
				{% endfor %}
				</ul>
			</div>
			<div class="row">
				<h3 class="text-center mb-3">My Events</h3>
				<ul class="list-group col-lg-2 offset-lg-5 text-center">
				{% for eventitem in eventitem_list %}
					<li class="list-group-item">
						<a href="{% url 'todolist:vieweventitem' eventitem.id %}" class="text-decoration-none">{{eventitem.event_name}}</a>
					</li>
				{% endfor %}
				</ul>
			</div>
		</div>

	{% elif user.is_anonymous == True %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
	{% else %}
		<p>No tasks have been created.</p>

	{% endif %}
{% endblock %}

todolist/templates/todolist/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Login</h1>
			{% if error == True %}
				<p class="text-danger">Invalid user credentials, please check your username and password</p>
			{% endif %}
			<form action="{% url 'todolist:login' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<label for="username">Username:</label>
					<input class="form-control" id="username" type="text" name="username" value="{{ username }}" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="password">Password:</label>
					<input class="form-control" id="password" type="password" name="password" value="{{ password }}" maxlength="20" required>
				</div>

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Login">
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}





<!-- {% if is_user_authenticated == False %}
	<h1>Something went Wrong</h1>
	<p>Please conteact your administrator or reset your password.</p>
	<a href="{% url 'todolist:index' %}"
{% endif %} -->

todolist/templates/todolist/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-6 offset-3">
			<h1 class="text-center my-3">Register</h1>
			{% if is_user_registered == False %}
				<h1>Duplicate User Found!</h1>
				<p>A duplicate user has been found, user creation unsuccessful</p>
			{% else %}
				<h1>User Successfully Created!</h1>
				<p>The account for {{first_name}} {{last_name}} has been successfully created.</p>

			{% endif %}
			<form action="{% url 'todolist:register' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<label for="username">Username:</label>
					<input class="form-control" id="username" type="text" name="username" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="password">Password:</label>
					<input class="form-control" id="password" type="password" name="password" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="confirm_password">Confirm Password:</label>
					<input class="form-control" id="confirm_password" type="password" name="confirm_password" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="first_name">First Name:</label>
					<input class="form-control" id="first_name" type="text" name="first_name" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="last_name">Last Name:</label>
					<input class="form-control" id="last_name" type="text" name="last_name" maxlength="20" required>
				</div>

				<div class="mb-3">
					<label for="email">Email:</label>
					<input class="form-control" id="email" type="email" name="email" maxlength="20" required>
				</div>

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Register">
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}






<!-- {% if is_user_registered == False %}
	<h1>Duplicate User Found!</h1>
	<p>A duplicate user has been found, user creation unsuccessful</p>
{% else %}
	<h1>User Successfully Created!</h1>
	<p>The account for {{first_name}} {{last_name}} has been successfully created.</p>

{% endif %} -->

todolist/templates/todolist/todoitem.html
{% extends 'base.html' %}

{% block title %}{{ task_name }}{% endblock %}

{% block content %}
<div class="text-center my-3">
	<h1>{{ task_name }}</h1>
	<h3>Description</h3>
	<p>{{ description }}</p>
	<h3>Status</h3>
	<p>{{ status }}</p>

	<button class="btn btn-primary mx-1 text-decoration-none">
		<a href="{% url 'todolist:update_task' id %}" class="text-light text-decoration-none">Edit Task</a>
	</button>

		<button class="btn btn-danger mx-1 text-decoration-none">
		<a href="{% url 'todolist:delete_task' id %}" class="text-light text-decoration-none">Delete Task</a>
	</button>

	<button class="btn btn-warning mx-1 text-decoration-none">
		<a href="{% url 'todolist:index' %}" class="text-light text-decoration-none">Back to Tasks</a>
	</button>

</div>

{% endblock %}

todolist/templates/todolist/update_task.html
{% extends 'base.html' %}

{% block title %}Update Task{% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Update Task</h1>
				{% if error == True %}
					<p class="text-danger">Task not found</p>
				{% endif %}
				<form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
					{% csrf_token %}

					<div class="mb-3">
						<label for="task_name">Task Name: </label>
						<input class="form-control" id="task_name" type="text" name="task_name" value="{{ task_name }}" maxlength="50" required>
					</div>

					<div class="mb-3">
						<label for="description">Description: </label>
						<textarea class="form-control" name="description" required>{{ description }}</textarea>
					</div>

					<div class="mb-3">
						<label for="status">Status: </label>
						<input class="form-control" id="status" type="text" name="status" value="{{ status }}" maxlength="50" required>
					</div>

					<div class="text-center">
						<input class="btn btn-success" type="submit" value="Update Task">
					</div>
				</form>
			</div>
		</div>
	</div>
	{% else %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}">here</a></p>
	{% endif %}
{% endblock %}